#!/bin/bash

###############################################################################
# Banking Suite V3 - Direct Deployment Script
# 
# Deploys from /root/banking/banking-v3 with pre-configured settings
# Stops the old banking-suite containers and deploys the new version
#
# Usage:
#   1. Upload the banking-v3 folder to your VPS at /root/banking/banking-v3
#   2. chmod +x deploy-vpsv3.sh
#   3. ./deploy-vpsv3.sh
###############################################################################

set -e  # Exit on error

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${BLUE}ℹ${NC} $1"; }
print_success() { echo -e "${GREEN}✓${NC} $1"; }
print_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
print_error() { echo -e "${RED}✗${NC} $1"; }
print_header() {
    echo ""
    echo -e "${BLUE}════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}════════════════════════════════════════════${NC}"
    echo ""
}

# Check root
if [ "$EUID" -ne 0 ]; then 
    print_error "Please run as root"
    exit 1
fi

clear
print_header "Banking Suite V3 - Deployment Script"

# Configuration - CHANGE THESE VALUES
DOMAIN="bankingsuite.codingcartel.li"
ADMIN_USERNAME="admin"
ADMIN_PASSWORD='qz^X5rp%KjH2SRlo'
ADMIN_EMAIL="admin@codingcartel.li"
APP_DIR="/root/banking/banking-v3"
CONTAINER_NAME="banking-suite-v3"
OLD_CONTAINER_NAME="banking-suite"
OLD_CONTAINER_V2="banking-suite-v2"

print_info "Domain: $DOMAIN"
print_info "App Directory: $APP_DIR"
print_info "New Container: $CONTAINER_NAME"
print_info "Old Containers to stop: $OLD_CONTAINER_NAME, $OLD_CONTAINER_V2"
echo ""
read -p "Press Enter to start deployment..."

# Step 1: Verify project exists
print_header "Step 1: Verifying Project Files"
if [ ! -d "$APP_DIR" ]; then
    print_error "Project directory not found: $APP_DIR"
    print_info "Please upload your project first:"
    print_info "  Upload banking-v3 folder to /root/banking/banking-v3"
    exit 1
fi

cd $APP_DIR

if [ ! -f "Dockerfile" ]; then
    print_error "Dockerfile not found in $APP_DIR"
    exit 1
fi

print_success "Project files verified"

# Step 2: Create Environment File
print_header "Step 2: Creating Environment Configuration"
cat > $APP_DIR/.env.production <<EOF
# Production Environment Variables - Multi-Banking Panel V3
# Generated by deploy-vpsv3.sh on $(date)

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
PORT=3001
NODE_ENV=production

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================
JWT_SECRET=554904df7d390d8d0ad2271b053ce66c53a05a11c7190dfbfae3c91fe08eb6c1f47e8f6aab29e459e4ee0549276dee63217416d66a39746899d9ec7c787a10c4
SESSION_SECRET=bd085aa9ce1900699150ff23e490614d3c98e4fd1213e304da544bd14d0a04d838012cc1bc4e742c30053fabd104efb9fc8b65b172d94835a97c3b2009f604c0
ENCRYPTION_KEY=428944a9164c2838be9d5f9c0a124537
ENCRYPTION_IV=4f37f6e7a72432ad

# =============================================================================
# ADMIN CONFIGURATION
# =============================================================================
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_EMAIL=$ADMIN_EMAIL

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
DB_PATH=/app/data/database.sqlite

# =============================================================================
# URL CONFIGURATION
# =============================================================================
SERVER_URL=https://$DOMAIN
CLIENT_URL=https://$DOMAIN
CORS_ORIGIN=https://$DOMAIN
BACKEND_URL=http://localhost:3001
TEMPLATE_BASE_URL=https://$DOMAIN

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
EMAIL_HOST=smtp.example.com
EMAIL_PORT=587
EMAIL_SECURE=false
EMAIL_USER=
EMAIL_PASS=
EMAIL_FROM=no-reply@$DOMAIN
DEFAULT_FROM_EMAIL=no-reply@$DOMAIN
DEFAULT_FROM_NAME=Multi-Banking Panel

# =============================================================================
# FILE UPLOAD CONFIGURATION
# =============================================================================
UPLOAD_DIR=/app/uploads
MAX_FILE_SIZE=10485760
ALLOWED_FILE_TYPES=image/jpeg,image/png,application/pdf

# =============================================================================
# SESSION CONFIGURATION
# =============================================================================
SESSION_EXPIRE_HOURS=24

# =============================================================================
# SECURITY SETTINGS
# =============================================================================
TRUST_PROXY=true
TRUSTED_PROXIES=

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOG_LEVEL=info
LOG_FILE=/app/logs/app.log

# =============================================================================
# RATE LIMITING
# =============================================================================
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# =============================================================================
# CACHE CONFIGURATION
# =============================================================================
CACHE_TTL=3600
EOF

chmod 600 $APP_DIR/.env.production
print_success "Environment file created"

# Step 3: Stop Old Containers and Conflicting Services
print_header "Step 3: Stopping Old Containers & Conflicting Services"

# Stop Dokploy if running
if docker ps | grep -q dokploy-traefik; then
    print_info "Stopping Dokploy Traefik..."
    docker stop dokploy-traefik 2>/dev/null || true
fi

DOKPLOY_CONTAINERS=$(docker ps -q --filter "name=dokploy" 2>/dev/null || true)
if [ -n "$DOKPLOY_CONTAINERS" ]; then
    print_info "Stopping Dokploy containers..."
    docker stop $DOKPLOY_CONTAINERS 2>/dev/null || true
fi

# Stop OLD banking-suite container (v1)
if docker ps -a | grep -q "$OLD_CONTAINER_NAME"; then
    print_info "Stopping old $OLD_CONTAINER_NAME container..."
    docker stop $OLD_CONTAINER_NAME 2>/dev/null || true
    docker rm $OLD_CONTAINER_NAME 2>/dev/null || true
    print_success "Old $OLD_CONTAINER_NAME container stopped and removed"
fi

# Stop OLD banking-suite-v2 container
if docker ps -a | grep -q "$OLD_CONTAINER_V2"; then
    print_info "Stopping old $OLD_CONTAINER_V2 container..."
    docker stop $OLD_CONTAINER_V2 2>/dev/null || true
    docker rm $OLD_CONTAINER_V2 2>/dev/null || true
    print_success "Old $OLD_CONTAINER_V2 container stopped and removed"
fi

# Stop existing v3 container if exists (for re-deployment)
if docker ps -a | grep -q "$CONTAINER_NAME"; then
    print_info "Removing existing $CONTAINER_NAME container..."
    docker stop $CONTAINER_NAME 2>/dev/null || true
    docker rm $CONTAINER_NAME 2>/dev/null || true
fi

print_success "Conflicting services stopped"

# Step 4: Build Docker Image
print_header "Step 4: Building Docker Image"
print_info "This will take 5-10 minutes..."
print_info "Building with multi-stage Dockerfile (Frontend + Backend + Mailer)..."

docker build -t banking-suite-v3:latest $APP_DIR

print_success "Docker image built successfully"

# Step 5: Start Application
print_header "Step 5: Starting Application Container"

docker run -d \
    --name $CONTAINER_NAME \
    --restart unless-stopped \
    -p 127.0.0.1:8080:80 \
    -v banking-v3-data:/app/data \
    -v banking-v3-uploads:/app/uploads \
    -v banking-v3-logs:/app/logs \
    --env-file $APP_DIR/.env.production \
    banking-suite-v3:latest

sleep 10

if docker ps | grep -q $CONTAINER_NAME; then
    print_success "Application started successfully"
    print_info "Container exposes:"
    print_info "  - Port 80: Nginx (Frontend)"
    print_info "  - Internal: Backend (3001) + Mailer (3002)"
else
    print_error "Failed to start application"
    print_info "Check logs: docker logs $CONTAINER_NAME"
    exit 1
fi

# Step 6: Install Nginx & Certbot
print_header "Step 6: Installing Nginx & Certbot"
apt update -y
apt install -y nginx certbot python3-certbot-nginx
print_success "Nginx and Certbot installed"

# Step 7: Configure Nginx
print_header "Step 7: Configuring Nginx"

# Stop Apache if running
systemctl stop apache2 2>/dev/null || true
systemctl disable apache2 2>/dev/null || true

cat > /etc/nginx/sites-available/banking-suite-v3 <<EOF
server {
    listen 80;
    server_name $DOMAIN;

    client_max_body_size 10M;

    # Frontend and API are all served through the container's Nginx
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }
}
EOF

# Remove old configs and enable new one
rm -f /etc/nginx/sites-enabled/banking-suite
rm -f /etc/nginx/sites-enabled/banking-suite-v2
ln -sf /etc/nginx/sites-available/banking-suite-v3 /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

nginx -t
systemctl restart nginx
print_success "Nginx configured and started"

# Step 8: Configure Firewall
print_header "Step 8: Configuring Firewall"
ufw allow 22/tcp 2>/dev/null || true
ufw allow 80/tcp 2>/dev/null || true
ufw allow 443/tcp 2>/dev/null || true
print_success "Firewall rules configured"

# Step 9: Setup SSL
print_header "Step 9: Setting Up SSL Certificate"
print_info "Obtaining Let's Encrypt SSL certificate..."

certbot --nginx \
    -d $DOMAIN \
    --email $ADMIN_EMAIL \
    --agree-tos \
    --non-interactive \
    --redirect

if [ $? -eq 0 ]; then
    print_success "SSL certificate installed successfully"
    systemctl enable certbot.timer 2>/dev/null || true
    systemctl start certbot.timer 2>/dev/null || true
    print_success "SSL auto-renewal configured"
else
    print_warning "SSL setup failed (may already exist)"
    print_info "You can run manually: certbot --nginx -d $DOMAIN"
fi

# Get Server IP
SERVER_IP=$(curl -s ifconfig.me || curl -s icanhazip.com || echo "Unknown")

# Step 10: Verify Services
print_header "Step 10: Verifying Services"

# Check if container is healthy
sleep 5
HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' $CONTAINER_NAME 2>/dev/null || echo "no-health")
if [ "$HEALTH_STATUS" = "healthy" ]; then
    print_success "Container health check: PASSED"
elif [ "$HEALTH_STATUS" = "starting" ]; then
    print_info "Container health check: Starting (will be healthy in ~40s)"
else
    print_warning "Container health check: $HEALTH_STATUS (checking logs...)"
fi

# Test internal services
print_info "Checking internal services..."
docker exec $CONTAINER_NAME sh -c "curl -s http://localhost:3001/api/health > /dev/null && echo 'Backend: OK' || echo 'Backend: Starting...'"
docker exec $CONTAINER_NAME sh -c "curl -s http://localhost:3002/health > /dev/null && echo 'Mailer: OK' || echo 'Mailer: Starting...'"

# Final Summary
print_header "✅ Deployment Complete!"
echo ""
print_success "Banking Suite V3 is live!"
echo ""
print_info "Access Information:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  🌐 Admin Panel: ${GREEN}https://$DOMAIN/admin${NC}"
echo -e "  👤 Username:    ${GREEN}$ADMIN_USERNAME${NC}"
echo -e "  🔑 Password:    ${GREEN}$ADMIN_PASSWORD${NC}"
echo -e "  📡 Server IP:   ${GREEN}$SERVER_IP${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
print_warning "Important Notes:"
echo "  • Main page shows 403 error (anti-bot protection - this is normal)"
echo "  • Save your credentials securely"
echo "  • V3 includes: Frontend + Backend + Mailer in one container"
echo "  • Old banking-suite and banking-suite-v2 containers have been stopped"
echo ""
print_info "Services Running:"
echo "  • Nginx (Frontend): Port 80 → proxied to 8080"
echo "  • Backend API: Internal port 3001"
echo "  • Mailer Service: Internal port 3002"
echo ""
print_info "Useful Commands:"
echo "  • View logs:     docker logs -f $CONTAINER_NAME"
echo "  • Restart app:   docker restart $CONTAINER_NAME"
echo "  • Stop app:      docker stop $CONTAINER_NAME"
echo "  • Shell access:  docker exec -it $CONTAINER_NAME sh"
echo "  • Backend logs:  docker exec $CONTAINER_NAME cat /app/logs/app.log"
echo "  • Nginx logs:    tail -f /var/log/nginx/error.log"
echo ""
print_info "Update Application:"
echo "  cd $APP_DIR"
echo "  git pull"
echo "  docker build -t banking-suite-v3:latest ."
echo "  docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME"
echo "  # Then re-run this script"
echo ""
print_info "Data Volumes (persistent):"
echo "  • banking-v3-data    - Database"
echo "  • banking-v3-uploads - Uploaded files"
echo "  • banking-v3-logs    - Application logs"
echo ""
print_header "Deployment Completed Successfully!"
echo ""
